import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Button from "@/components/ui/Button/Button";

const openSans = localFont({
  src: "./fonts/OpenSans-VariableFont_wdth,wght.woff2",
  variable: "--font-open-sans",
  weight: "100 900",
});

const roboto = localFont({
  src: "./fonts/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.woff2",
  variable: "--font-roboto",
  weight: "100 900",
});

const yellowtail = localFont({
  src: "./fonts/Yellowtail-Regular.woff2",
  variable: "--font-yellowtail",
  weight: "400",
});

export const metadata: Metadata = {
  title: "organic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${roboto.variable} ${yellowtail.variable} antialiased`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
